POST http://localhost:8081/category/admin/add
Content-Type: application/json

{
  "name" : "phone",
  "description" : "simple design"
}

###
GET http://localhost:8081/category/get

###
POST http://localhost:8081/category/admin/edit/1
Content-Type: application/json

{
  "name" : "phones",
  "description" : "modern phones"
}