POST http://localhost:8081/category/admin/add/cars

###
GET http://localhost:8081/category/get

###
POST http://localhost:8081/category/admin/edit/1
Content-Type: application/json

{
  "name" : "phones",
  "description" : "modern phones"
}